IMAGE_NAME = "bento/debian-12"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end

    config.vm.define "debian" do |debian|
        debian.vm.box = IMAGE_NAME

        # NAT + port forwarding pro SSH
        debian.vm.network "forwarded_port", guest: 22, host: 2206, host_ip: "127.0.0.1"

        # Host-only síť – VM bude vidět pfSense i ostatní VM
        debian.vm.network "private_network", type: "dhcp"

        debian.vm.hostname = "debian"
    end
end
